print("jinhui를 넣으면",bool('jinhui'))
print("''을 넣으면", bool(''))
print("공백을 넣으면",bool( ))
print("아무것도 안 넣으면",bool())
print("1 을 넣으면",bool(1))
print("0 을 넣으면",bool(0))
print("None 을 넣으면",bool(None))
print("[] 을 넣으면",bool([]))
print("[1,2,'banana'] 을 넣으면",bool([1,2,"banana"]))
print("{} 을 넣으면",bool({}))
